// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/demo.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Meta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{0}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Coord struct {
	Latitude             string   `protobuf:"bytes,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            string   `protobuf:"bytes,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coord) Reset()         { *m = Coord{} }
func (m *Coord) String() string { return proto.CompactTextString(m) }
func (*Coord) ProtoMessage()    {}
func (*Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{3}
}

func (m *Coord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coord.Unmarshal(m, b)
}
func (m *Coord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coord.Marshal(b, m, deterministic)
}
func (m *Coord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coord.Merge(m, src)
}
func (m *Coord) XXX_Size() int {
	return xxx_messageInfo_Coord.Size(m)
}
func (m *Coord) XXX_DiscardUnknown() {
	xxx_messageInfo_Coord.DiscardUnknown(m)
}

var xxx_messageInfo_Coord proto.InternalMessageInfo

func (m *Coord) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *Coord) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type UserGetRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetRequest) Reset()         { *m = UserGetRequest{} }
func (m *UserGetRequest) String() string { return proto.CompactTextString(m) }
func (*UserGetRequest) ProtoMessage()    {}
func (*UserGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{5}
}

func (m *UserGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetRequest.Unmarshal(m, b)
}
func (m *UserGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetRequest.Marshal(b, m, deterministic)
}
func (m *UserGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetRequest.Merge(m, src)
}
func (m *UserGetRequest) XXX_Size() int {
	return xxx_messageInfo_UserGetRequest.Size(m)
}
func (m *UserGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetRequest proto.InternalMessageInfo

func (m *UserGetRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserGetResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetResponse) Reset()         { *m = UserGetResponse{} }
func (m *UserGetResponse) String() string { return proto.CompactTextString(m) }
func (*UserGetResponse) ProtoMessage()    {}
func (*UserGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{6}
}

func (m *UserGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetResponse.Unmarshal(m, b)
}
func (m *UserGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetResponse.Marshal(b, m, deterministic)
}
func (m *UserGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetResponse.Merge(m, src)
}
func (m *UserGetResponse) XXX_Size() int {
	return xxx_messageInfo_UserGetResponse.Size(m)
}
func (m *UserGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetResponse proto.InternalMessageInfo

func (m *UserGetResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserGetResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserGetResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserGetByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetByEmailRequest) Reset()         { *m = UserGetByEmailRequest{} }
func (m *UserGetByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*UserGetByEmailRequest) ProtoMessage()    {}
func (*UserGetByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{7}
}

func (m *UserGetByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetByEmailRequest.Unmarshal(m, b)
}
func (m *UserGetByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetByEmailRequest.Marshal(b, m, deterministic)
}
func (m *UserGetByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetByEmailRequest.Merge(m, src)
}
func (m *UserGetByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_UserGetByEmailRequest.Size(m)
}
func (m *UserGetByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetByEmailRequest proto.InternalMessageInfo

func (m *UserGetByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserGetByEmailResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetByEmailResponse) Reset()         { *m = UserGetByEmailResponse{} }
func (m *UserGetByEmailResponse) String() string { return proto.CompactTextString(m) }
func (*UserGetByEmailResponse) ProtoMessage()    {}
func (*UserGetByEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{8}
}

func (m *UserGetByEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetByEmailResponse.Unmarshal(m, b)
}
func (m *UserGetByEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetByEmailResponse.Marshal(b, m, deterministic)
}
func (m *UserGetByEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetByEmailResponse.Merge(m, src)
}
func (m *UserGetByEmailResponse) XXX_Size() int {
	return xxx_messageInfo_UserGetByEmailResponse.Size(m)
}
func (m *UserGetByEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetByEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetByEmailResponse proto.InternalMessageInfo

func (m *UserGetByEmailResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserGetByEmailResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserGetByEmailResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserCreateRequest struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateRequest) Reset()         { *m = UserCreateRequest{} }
func (m *UserCreateRequest) String() string { return proto.CompactTextString(m) }
func (*UserCreateRequest) ProtoMessage()    {}
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{9}
}

func (m *UserCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateRequest.Unmarshal(m, b)
}
func (m *UserCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateRequest.Marshal(b, m, deterministic)
}
func (m *UserCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateRequest.Merge(m, src)
}
func (m *UserCreateRequest) XXX_Size() int {
	return xxx_messageInfo_UserCreateRequest.Size(m)
}
func (m *UserCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateRequest proto.InternalMessageInfo

func (m *UserCreateRequest) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserCreateResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateResponse) Reset()         { *m = UserCreateResponse{} }
func (m *UserCreateResponse) String() string { return proto.CompactTextString(m) }
func (*UserCreateResponse) ProtoMessage()    {}
func (*UserCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{10}
}

func (m *UserCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateResponse.Unmarshal(m, b)
}
func (m *UserCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateResponse.Marshal(b, m, deterministic)
}
func (m *UserCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateResponse.Merge(m, src)
}
func (m *UserCreateResponse) XXX_Size() int {
	return xxx_messageInfo_UserCreateResponse.Size(m)
}
func (m *UserCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateResponse proto.InternalMessageInfo

func (m *UserCreateResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserCreateResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserCreateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserVerifyPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserVerifyPasswordRequest) Reset()         { *m = UserVerifyPasswordRequest{} }
func (m *UserVerifyPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UserVerifyPasswordRequest) ProtoMessage()    {}
func (*UserVerifyPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{11}
}

func (m *UserVerifyPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVerifyPasswordRequest.Unmarshal(m, b)
}
func (m *UserVerifyPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVerifyPasswordRequest.Marshal(b, m, deterministic)
}
func (m *UserVerifyPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVerifyPasswordRequest.Merge(m, src)
}
func (m *UserVerifyPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UserVerifyPasswordRequest.Size(m)
}
func (m *UserVerifyPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVerifyPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserVerifyPasswordRequest proto.InternalMessageInfo

func (m *UserVerifyPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserVerifyPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserVerifyPasswordResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserVerifyPasswordResponse) Reset()         { *m = UserVerifyPasswordResponse{} }
func (m *UserVerifyPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UserVerifyPasswordResponse) ProtoMessage()    {}
func (*UserVerifyPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{12}
}

func (m *UserVerifyPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVerifyPasswordResponse.Unmarshal(m, b)
}
func (m *UserVerifyPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVerifyPasswordResponse.Marshal(b, m, deterministic)
}
func (m *UserVerifyPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVerifyPasswordResponse.Merge(m, src)
}
func (m *UserVerifyPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UserVerifyPasswordResponse.Size(m)
}
func (m *UserVerifyPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVerifyPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserVerifyPasswordResponse proto.InternalMessageInfo

func (m *UserVerifyPasswordResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *UserVerifyPasswordResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListRequest) Reset()         { *m = UserListRequest{} }
func (m *UserListRequest) String() string { return proto.CompactTextString(m) }
func (*UserListRequest) ProtoMessage()    {}
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{13}
}

func (m *UserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRequest.Unmarshal(m, b)
}
func (m *UserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRequest.Marshal(b, m, deterministic)
}
func (m *UserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRequest.Merge(m, src)
}
func (m *UserListRequest) XXX_Size() int {
	return xxx_messageInfo_UserListRequest.Size(m)
}
func (m *UserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRequest proto.InternalMessageInfo

type UserListResponse struct {
	Data                 []*User  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{14}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserListResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserListResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{15}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthVerifyTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthVerifyTokenRequest) Reset()         { *m = AuthVerifyTokenRequest{} }
func (m *AuthVerifyTokenRequest) String() string { return proto.CompactTextString(m) }
func (*AuthVerifyTokenRequest) ProtoMessage()    {}
func (*AuthVerifyTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{16}
}

func (m *AuthVerifyTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthVerifyTokenRequest.Unmarshal(m, b)
}
func (m *AuthVerifyTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthVerifyTokenRequest.Marshal(b, m, deterministic)
}
func (m *AuthVerifyTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthVerifyTokenRequest.Merge(m, src)
}
func (m *AuthVerifyTokenRequest) XXX_Size() int {
	return xxx_messageInfo_AuthVerifyTokenRequest.Size(m)
}
func (m *AuthVerifyTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthVerifyTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthVerifyTokenRequest proto.InternalMessageInfo

func (m *AuthVerifyTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthVerifyTokenResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthVerifyTokenResponse) Reset()         { *m = AuthVerifyTokenResponse{} }
func (m *AuthVerifyTokenResponse) String() string { return proto.CompactTextString(m) }
func (*AuthVerifyTokenResponse) ProtoMessage()    {}
func (*AuthVerifyTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{17}
}

func (m *AuthVerifyTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthVerifyTokenResponse.Unmarshal(m, b)
}
func (m *AuthVerifyTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthVerifyTokenResponse.Marshal(b, m, deterministic)
}
func (m *AuthVerifyTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthVerifyTokenResponse.Merge(m, src)
}
func (m *AuthVerifyTokenResponse) XXX_Size() int {
	return xxx_messageInfo_AuthVerifyTokenResponse.Size(m)
}
func (m *AuthVerifyTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthVerifyTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthVerifyTokenResponse proto.InternalMessageInfo

func (m *AuthVerifyTokenResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *AuthVerifyTokenResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type AuthLoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthLoginRequest) Reset()         { *m = AuthLoginRequest{} }
func (m *AuthLoginRequest) String() string { return proto.CompactTextString(m) }
func (*AuthLoginRequest) ProtoMessage()    {}
func (*AuthLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{18}
}

func (m *AuthLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLoginRequest.Unmarshal(m, b)
}
func (m *AuthLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLoginRequest.Marshal(b, m, deterministic)
}
func (m *AuthLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLoginRequest.Merge(m, src)
}
func (m *AuthLoginRequest) XXX_Size() int {
	return xxx_messageInfo_AuthLoginRequest.Size(m)
}
func (m *AuthLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLoginRequest proto.InternalMessageInfo

func (m *AuthLoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthLoginResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *Token   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthLoginResponse) Reset()         { *m = AuthLoginResponse{} }
func (m *AuthLoginResponse) String() string { return proto.CompactTextString(m) }
func (*AuthLoginResponse) ProtoMessage()    {}
func (*AuthLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{19}
}

func (m *AuthLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLoginResponse.Unmarshal(m, b)
}
func (m *AuthLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLoginResponse.Marshal(b, m, deterministic)
}
func (m *AuthLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLoginResponse.Merge(m, src)
}
func (m *AuthLoginResponse) XXX_Size() int {
	return xxx_messageInfo_AuthLoginResponse.Size(m)
}
func (m *AuthLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLoginResponse proto.InternalMessageInfo

func (m *AuthLoginResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AuthLoginResponse) GetMeta() *Token {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *AuthLoginResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type AuthSignupRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthSignupRequest) Reset()         { *m = AuthSignupRequest{} }
func (m *AuthSignupRequest) String() string { return proto.CompactTextString(m) }
func (*AuthSignupRequest) ProtoMessage()    {}
func (*AuthSignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{20}
}

func (m *AuthSignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSignupRequest.Unmarshal(m, b)
}
func (m *AuthSignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSignupRequest.Marshal(b, m, deterministic)
}
func (m *AuthSignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSignupRequest.Merge(m, src)
}
func (m *AuthSignupRequest) XXX_Size() int {
	return xxx_messageInfo_AuthSignupRequest.Size(m)
}
func (m *AuthSignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSignupRequest proto.InternalMessageInfo

func (m *AuthSignupRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type AuthSignupResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *Token   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthSignupResponse) Reset()         { *m = AuthSignupResponse{} }
func (m *AuthSignupResponse) String() string { return proto.CompactTextString(m) }
func (*AuthSignupResponse) ProtoMessage()    {}
func (*AuthSignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{21}
}

func (m *AuthSignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSignupResponse.Unmarshal(m, b)
}
func (m *AuthSignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSignupResponse.Marshal(b, m, deterministic)
}
func (m *AuthSignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSignupResponse.Merge(m, src)
}
func (m *AuthSignupResponse) XXX_Size() int {
	return xxx_messageInfo_AuthSignupResponse.Size(m)
}
func (m *AuthSignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSignupResponse proto.InternalMessageInfo

func (m *AuthSignupResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AuthSignupResponse) GetMeta() *Token {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *AuthSignupResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type AuthLogoutRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthLogoutRequest) Reset()         { *m = AuthLogoutRequest{} }
func (m *AuthLogoutRequest) String() string { return proto.CompactTextString(m) }
func (*AuthLogoutRequest) ProtoMessage()    {}
func (*AuthLogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{22}
}

func (m *AuthLogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLogoutRequest.Unmarshal(m, b)
}
func (m *AuthLogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLogoutRequest.Marshal(b, m, deterministic)
}
func (m *AuthLogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLogoutRequest.Merge(m, src)
}
func (m *AuthLogoutRequest) XXX_Size() int {
	return xxx_messageInfo_AuthLogoutRequest.Size(m)
}
func (m *AuthLogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLogoutRequest proto.InternalMessageInfo

func (m *AuthLogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthLogoutResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthLogoutResponse) Reset()         { *m = AuthLogoutResponse{} }
func (m *AuthLogoutResponse) String() string { return proto.CompactTextString(m) }
func (*AuthLogoutResponse) ProtoMessage()    {}
func (*AuthLogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{23}
}

func (m *AuthLogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLogoutResponse.Unmarshal(m, b)
}
func (m *AuthLogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLogoutResponse.Marshal(b, m, deterministic)
}
func (m *AuthLogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLogoutResponse.Merge(m, src)
}
func (m *AuthLogoutResponse) XXX_Size() int {
	return xxx_messageInfo_AuthLogoutResponse.Size(m)
}
func (m *AuthLogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLogoutResponse proto.InternalMessageInfo

func (m *AuthLogoutResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type AuthForgotPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthForgotPasswordRequest) Reset()         { *m = AuthForgotPasswordRequest{} }
func (m *AuthForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*AuthForgotPasswordRequest) ProtoMessage()    {}
func (*AuthForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{24}
}

func (m *AuthForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthForgotPasswordRequest.Unmarshal(m, b)
}
func (m *AuthForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *AuthForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthForgotPasswordRequest.Merge(m, src)
}
func (m *AuthForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_AuthForgotPasswordRequest.Size(m)
}
func (m *AuthForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthForgotPasswordRequest proto.InternalMessageInfo

func (m *AuthForgotPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AuthForgotPasswordResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthForgotPasswordResponse) Reset()         { *m = AuthForgotPasswordResponse{} }
func (m *AuthForgotPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*AuthForgotPasswordResponse) ProtoMessage()    {}
func (*AuthForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{25}
}

func (m *AuthForgotPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthForgotPasswordResponse.Unmarshal(m, b)
}
func (m *AuthForgotPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthForgotPasswordResponse.Marshal(b, m, deterministic)
}
func (m *AuthForgotPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthForgotPasswordResponse.Merge(m, src)
}
func (m *AuthForgotPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_AuthForgotPasswordResponse.Size(m)
}
func (m *AuthForgotPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthForgotPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthForgotPasswordResponse proto.InternalMessageInfo

func (m *AuthForgotPasswordResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type AuthRecoverPasswordRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRecoverPasswordRequest) Reset()         { *m = AuthRecoverPasswordRequest{} }
func (m *AuthRecoverPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRecoverPasswordRequest) ProtoMessage()    {}
func (*AuthRecoverPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{26}
}

func (m *AuthRecoverPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRecoverPasswordRequest.Unmarshal(m, b)
}
func (m *AuthRecoverPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRecoverPasswordRequest.Marshal(b, m, deterministic)
}
func (m *AuthRecoverPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRecoverPasswordRequest.Merge(m, src)
}
func (m *AuthRecoverPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRecoverPasswordRequest.Size(m)
}
func (m *AuthRecoverPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRecoverPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRecoverPasswordRequest proto.InternalMessageInfo

func (m *AuthRecoverPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthRecoverPasswordResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRecoverPasswordResponse) Reset()         { *m = AuthRecoverPasswordResponse{} }
func (m *AuthRecoverPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*AuthRecoverPasswordResponse) ProtoMessage()    {}
func (*AuthRecoverPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{27}
}

func (m *AuthRecoverPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRecoverPasswordResponse.Unmarshal(m, b)
}
func (m *AuthRecoverPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRecoverPasswordResponse.Marshal(b, m, deterministic)
}
func (m *AuthRecoverPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRecoverPasswordResponse.Merge(m, src)
}
func (m *AuthRecoverPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_AuthRecoverPasswordResponse.Size(m)
}
func (m *AuthRecoverPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRecoverPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRecoverPasswordResponse proto.InternalMessageInfo

func (m *AuthRecoverPasswordResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Restaurant struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating               string   `protobuf:"bytes,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Open                 bool     `protobuf:"varint,5,opt,name=open,proto3" json:"open,omitempty"`
	PhotoReference       string   `protobuf:"bytes,6,opt,name=photo_reference,json=photoReference,proto3" json:"photo_reference,omitempty"`
	Coord                *Coord   `protobuf:"bytes,7,opt,name=coord,proto3" json:"coord,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Restaurant) Reset()         { *m = Restaurant{} }
func (m *Restaurant) String() string { return proto.CompactTextString(m) }
func (*Restaurant) ProtoMessage()    {}
func (*Restaurant) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{28}
}

func (m *Restaurant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant.Unmarshal(m, b)
}
func (m *Restaurant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant.Marshal(b, m, deterministic)
}
func (m *Restaurant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant.Merge(m, src)
}
func (m *Restaurant) XXX_Size() int {
	return xxx_messageInfo_Restaurant.Size(m)
}
func (m *Restaurant) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant proto.InternalMessageInfo

func (m *Restaurant) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Restaurant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Restaurant) GetRating() string {
	if m != nil {
		return m.Rating
	}
	return ""
}

func (m *Restaurant) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Restaurant) GetOpen() bool {
	if m != nil {
		return m.Open
	}
	return false
}

func (m *Restaurant) GetPhotoReference() string {
	if m != nil {
		return m.PhotoReference
	}
	return ""
}

func (m *Restaurant) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

type RestaurantListByCoordRequest struct {
	Coord                *Coord   `protobuf:"bytes,1,opt,name=coord,proto3" json:"coord,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestaurantListByCoordRequest) Reset()         { *m = RestaurantListByCoordRequest{} }
func (m *RestaurantListByCoordRequest) String() string { return proto.CompactTextString(m) }
func (*RestaurantListByCoordRequest) ProtoMessage()    {}
func (*RestaurantListByCoordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{29}
}

func (m *RestaurantListByCoordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantListByCoordRequest.Unmarshal(m, b)
}
func (m *RestaurantListByCoordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantListByCoordRequest.Marshal(b, m, deterministic)
}
func (m *RestaurantListByCoordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantListByCoordRequest.Merge(m, src)
}
func (m *RestaurantListByCoordRequest) XXX_Size() int {
	return xxx_messageInfo_RestaurantListByCoordRequest.Size(m)
}
func (m *RestaurantListByCoordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantListByCoordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantListByCoordRequest proto.InternalMessageInfo

func (m *RestaurantListByCoordRequest) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

func (m *RestaurantListByCoordRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type MetaRestaurantListByCoord struct {
	PageToken            string   `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaRestaurantListByCoord) Reset()         { *m = MetaRestaurantListByCoord{} }
func (m *MetaRestaurantListByCoord) String() string { return proto.CompactTextString(m) }
func (*MetaRestaurantListByCoord) ProtoMessage()    {}
func (*MetaRestaurantListByCoord) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{30}
}

func (m *MetaRestaurantListByCoord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaRestaurantListByCoord.Unmarshal(m, b)
}
func (m *MetaRestaurantListByCoord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaRestaurantListByCoord.Marshal(b, m, deterministic)
}
func (m *MetaRestaurantListByCoord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaRestaurantListByCoord.Merge(m, src)
}
func (m *MetaRestaurantListByCoord) XXX_Size() int {
	return xxx_messageInfo_MetaRestaurantListByCoord.Size(m)
}
func (m *MetaRestaurantListByCoord) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaRestaurantListByCoord.DiscardUnknown(m)
}

var xxx_messageInfo_MetaRestaurantListByCoord proto.InternalMessageInfo

func (m *MetaRestaurantListByCoord) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type RestaurantListByCoordResponse struct {
	Data                 []*Restaurant              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Meta                 *MetaRestaurantListByCoord `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error                     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RestaurantListByCoordResponse) Reset()         { *m = RestaurantListByCoordResponse{} }
func (m *RestaurantListByCoordResponse) String() string { return proto.CompactTextString(m) }
func (*RestaurantListByCoordResponse) ProtoMessage()    {}
func (*RestaurantListByCoordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{31}
}

func (m *RestaurantListByCoordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantListByCoordResponse.Unmarshal(m, b)
}
func (m *RestaurantListByCoordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantListByCoordResponse.Marshal(b, m, deterministic)
}
func (m *RestaurantListByCoordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantListByCoordResponse.Merge(m, src)
}
func (m *RestaurantListByCoordResponse) XXX_Size() int {
	return xxx_messageInfo_RestaurantListByCoordResponse.Size(m)
}
func (m *RestaurantListByCoordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantListByCoordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantListByCoordResponse proto.InternalMessageInfo

func (m *RestaurantListByCoordResponse) GetData() []*Restaurant {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RestaurantListByCoordResponse) GetMeta() *MetaRestaurantListByCoord {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RestaurantListByCoordResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type History struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Latitude             string   `protobuf:"bytes,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            string   `protobuf:"bytes,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *History) Reset()         { *m = History{} }
func (m *History) String() string { return proto.CompactTextString(m) }
func (*History) ProtoMessage()    {}
func (*History) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{32}
}

func (m *History) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_History.Unmarshal(m, b)
}
func (m *History) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_History.Marshal(b, m, deterministic)
}
func (m *History) XXX_Merge(src proto.Message) {
	xxx_messageInfo_History.Merge(m, src)
}
func (m *History) XXX_Size() int {
	return xxx_messageInfo_History.Size(m)
}
func (m *History) XXX_DiscardUnknown() {
	xxx_messageInfo_History.DiscardUnknown(m)
}

var xxx_messageInfo_History proto.InternalMessageInfo

func (m *History) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *History) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *History) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *History) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *History) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *History) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type HistoryListByUserIdRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryListByUserIdRequest) Reset()         { *m = HistoryListByUserIdRequest{} }
func (m *HistoryListByUserIdRequest) String() string { return proto.CompactTextString(m) }
func (*HistoryListByUserIdRequest) ProtoMessage()    {}
func (*HistoryListByUserIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{33}
}

func (m *HistoryListByUserIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryListByUserIdRequest.Unmarshal(m, b)
}
func (m *HistoryListByUserIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryListByUserIdRequest.Marshal(b, m, deterministic)
}
func (m *HistoryListByUserIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryListByUserIdRequest.Merge(m, src)
}
func (m *HistoryListByUserIdRequest) XXX_Size() int {
	return xxx_messageInfo_HistoryListByUserIdRequest.Size(m)
}
func (m *HistoryListByUserIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryListByUserIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryListByUserIdRequest proto.InternalMessageInfo

func (m *HistoryListByUserIdRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type HistoryListByUserIdResponse struct {
	Data                 []*History `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Meta                 *Meta      `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *HistoryListByUserIdResponse) Reset()         { *m = HistoryListByUserIdResponse{} }
func (m *HistoryListByUserIdResponse) String() string { return proto.CompactTextString(m) }
func (*HistoryListByUserIdResponse) ProtoMessage()    {}
func (*HistoryListByUserIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{34}
}

func (m *HistoryListByUserIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryListByUserIdResponse.Unmarshal(m, b)
}
func (m *HistoryListByUserIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryListByUserIdResponse.Marshal(b, m, deterministic)
}
func (m *HistoryListByUserIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryListByUserIdResponse.Merge(m, src)
}
func (m *HistoryListByUserIdResponse) XXX_Size() int {
	return xxx_messageInfo_HistoryListByUserIdResponse.Size(m)
}
func (m *HistoryListByUserIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryListByUserIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryListByUserIdResponse proto.InternalMessageInfo

func (m *HistoryListByUserIdResponse) GetData() []*History {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *HistoryListByUserIdResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *HistoryListByUserIdResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Meta)(nil), "proto.Meta")
	proto.RegisterType((*Error)(nil), "proto.Error")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*Coord)(nil), "proto.Coord")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*UserGetRequest)(nil), "proto.UserGetRequest")
	proto.RegisterType((*UserGetResponse)(nil), "proto.UserGetResponse")
	proto.RegisterType((*UserGetByEmailRequest)(nil), "proto.UserGetByEmailRequest")
	proto.RegisterType((*UserGetByEmailResponse)(nil), "proto.UserGetByEmailResponse")
	proto.RegisterType((*UserCreateRequest)(nil), "proto.UserCreateRequest")
	proto.RegisterType((*UserCreateResponse)(nil), "proto.UserCreateResponse")
	proto.RegisterType((*UserVerifyPasswordRequest)(nil), "proto.UserVerifyPasswordRequest")
	proto.RegisterType((*UserVerifyPasswordResponse)(nil), "proto.UserVerifyPasswordResponse")
	proto.RegisterType((*UserListRequest)(nil), "proto.UserListRequest")
	proto.RegisterType((*UserListResponse)(nil), "proto.UserListResponse")
	proto.RegisterType((*Token)(nil), "proto.Token")
	proto.RegisterType((*AuthVerifyTokenRequest)(nil), "proto.AuthVerifyTokenRequest")
	proto.RegisterType((*AuthVerifyTokenResponse)(nil), "proto.AuthVerifyTokenResponse")
	proto.RegisterType((*AuthLoginRequest)(nil), "proto.AuthLoginRequest")
	proto.RegisterType((*AuthLoginResponse)(nil), "proto.AuthLoginResponse")
	proto.RegisterType((*AuthSignupRequest)(nil), "proto.AuthSignupRequest")
	proto.RegisterType((*AuthSignupResponse)(nil), "proto.AuthSignupResponse")
	proto.RegisterType((*AuthLogoutRequest)(nil), "proto.AuthLogoutRequest")
	proto.RegisterType((*AuthLogoutResponse)(nil), "proto.AuthLogoutResponse")
	proto.RegisterType((*AuthForgotPasswordRequest)(nil), "proto.AuthForgotPasswordRequest")
	proto.RegisterType((*AuthForgotPasswordResponse)(nil), "proto.AuthForgotPasswordResponse")
	proto.RegisterType((*AuthRecoverPasswordRequest)(nil), "proto.AuthRecoverPasswordRequest")
	proto.RegisterType((*AuthRecoverPasswordResponse)(nil), "proto.AuthRecoverPasswordResponse")
	proto.RegisterType((*Restaurant)(nil), "proto.Restaurant")
	proto.RegisterType((*RestaurantListByCoordRequest)(nil), "proto.RestaurantListByCoordRequest")
	proto.RegisterType((*MetaRestaurantListByCoord)(nil), "proto.MetaRestaurantListByCoord")
	proto.RegisterType((*RestaurantListByCoordResponse)(nil), "proto.RestaurantListByCoordResponse")
	proto.RegisterType((*History)(nil), "proto.History")
	proto.RegisterType((*HistoryListByUserIdRequest)(nil), "proto.HistoryListByUserIdRequest")
	proto.RegisterType((*HistoryListByUserIdResponse)(nil), "proto.HistoryListByUserIdResponse")
}

func init() { proto.RegisterFile("proto/demo.proto", fileDescriptor_bf10b39337e838aa) }

var fileDescriptor_bf10b39337e838aa = []byte{
	// 1046 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdb, 0x6e, 0x1b, 0x45,
	0x18, 0xee, 0x3a, 0x5e, 0x3b, 0xfe, 0x8d, 0xdc, 0x78, 0x68, 0x13, 0x67, 0x9b, 0x80, 0x3b, 0x80,
	0x48, 0x2f, 0x08, 0xc2, 0xb4, 0x52, 0x55, 0x81, 0xc0, 0x0d, 0xe1, 0x20, 0xb5, 0x80, 0x36, 0xa4,
	0x17, 0x20, 0x11, 0x0d, 0xde, 0xa9, 0xbb, 0x22, 0xde, 0x59, 0x66, 0xc7, 0x29, 0x2e, 0x12, 0x97,
	0x3c, 0x04, 0x57, 0x5c, 0xf3, 0x1a, 0xbc, 0x06, 0x6f, 0xc2, 0x0d, 0x9a, 0xd3, 0x7a, 0xd6, 0xbb,
	0x76, 0x13, 0x4a, 0x73, 0xb5, 0x3b, 0xff, 0x79, 0xfe, 0xf9, 0x0f, 0x1f, 0x6c, 0xa4, 0x9c, 0x09,
	0xf6, 0x6e, 0x44, 0x27, 0x6c, 0x5f, 0xfd, 0x22, 0x5f, 0x7d, 0x70, 0x03, 0xea, 0x0f, 0xa9, 0x20,
	0xf8, 0x0e, 0xf8, 0x87, 0x9c, 0x33, 0x8e, 0x10, 0xd4, 0x47, 0x2c, 0xa2, 0x3d, 0xaf, 0xef, 0xed,
	0xf9, 0xa1, 0xfa, 0x47, 0x3d, 0x68, 0x4e, 0x68, 0x96, 0x91, 0x31, 0xed, 0xd5, 0xfa, 0xde, 0x5e,
	0x2b, 0xb4, 0x47, 0xdc, 0x04, 0xff, 0x70, 0x92, 0x8a, 0x19, 0x1e, 0x82, 0x7f, 0xc0, 0x18, 0x8f,
	0x50, 0x00, 0xeb, 0xa7, 0x44, 0xc4, 0x62, 0x6a, 0x6c, 0xb4, 0xc2, 0xfc, 0x8c, 0x76, 0xa0, 0x75,
	0xca, 0x92, 0xb1, 0x66, 0x6a, 0x4b, 0x73, 0x02, 0xfe, 0xdd, 0x83, 0xfa, 0x71, 0x46, 0x39, 0xea,
	0x40, 0x2d, 0x8e, 0x8c, 0x72, 0x2d, 0x8e, 0xd0, 0x35, 0xf0, 0xe9, 0x84, 0xc4, 0xa7, 0x46, 0x45,
	0x1f, 0x64, 0xa0, 0x09, 0x99, 0xd0, 0xde, 0x9a, 0x22, 0xaa, 0x7f, 0xe9, 0x3c, 0x25, 0x59, 0xf6,
	0x94, 0xf1, 0xa8, 0x57, 0xd7, 0xce, 0xed, 0x19, 0xed, 0x02, 0x8c, 0x38, 0x25, 0x82, 0x46, 0x27,
	0x44, 0xf4, 0xfc, 0xbe, 0xb7, 0xb7, 0x16, 0xb6, 0x0c, 0x65, 0x28, 0x24, 0x7b, 0x9a, 0x46, 0x96,
	0xdd, 0xd0, 0x6c, 0x43, 0x19, 0x0a, 0x7c, 0x0b, 0x3a, 0x32, 0xb6, 0xcf, 0xa8, 0x08, 0xe9, 0x4f,
	0x53, 0x9a, 0x09, 0xb4, 0x05, 0xcd, 0x69, 0x46, 0xf9, 0x49, 0x1e, 0x6a, 0x43, 0x1e, 0xbf, 0x88,
	0xf0, 0x53, 0xb8, 0x9a, 0x8b, 0x66, 0x29, 0x4b, 0x32, 0x8a, 0x5e, 0x87, 0x7a, 0x44, 0x04, 0x51,
	0x82, 0xed, 0x41, 0x5b, 0x3f, 0xc1, 0xbe, 0x94, 0x0a, 0x15, 0x43, 0x0a, 0x4c, 0xa8, 0x20, 0xea,
	0x86, 0x73, 0x01, 0xf9, 0x32, 0xa1, 0x62, 0x20, 0x0c, 0x3e, 0x95, 0xef, 0xa3, 0xae, 0xdb, 0x1e,
	0xbc, 0x62, 0x24, 0xd4, 0x9b, 0x85, 0x9a, 0x85, 0xdf, 0x81, 0xeb, 0xc6, 0xf1, 0xfd, 0xd9, 0xa1,
	0xcc, 0x91, 0x0d, 0x35, 0x4f, 0xa0, 0xe7, 0x24, 0x10, 0xff, 0x0a, 0x9b, 0x8b, 0xe2, 0x97, 0x1a,
	0xee, 0x6d, 0xe8, 0x4a, 0x93, 0x07, 0xea, 0x09, 0x6c, 0xa8, 0xcf, 0x73, 0x8d, 0x9f, 0x01, 0x72,
	0xb5, 0x2e, 0x35, 0xe2, 0x87, 0xb0, 0x2d, 0x4d, 0x3e, 0xa2, 0x3c, 0x7e, 0x3c, 0xfb, 0xda, 0x14,
	0xd6, 0xca, 0x24, 0x17, 0x2a, 0xb2, 0x56, 0xac, 0x48, 0xfc, 0x08, 0x82, 0x2a, 0x73, 0xe6, 0x4a,
	0xd7, 0xc0, 0x3f, 0x23, 0xa7, 0xa6, 0xba, 0xd6, 0x43, 0x7d, 0x98, 0x87, 0x59, 0x5b, 0x1e, 0x66,
	0x57, 0x17, 0xe0, 0x83, 0x38, 0xb3, 0xc5, 0x8a, 0x7f, 0x86, 0x8d, 0x39, 0xa9, 0x94, 0xb3, 0xb5,
	0x97, 0x98, 0xb3, 0x5d, 0xf0, 0xbf, 0x61, 0x3f, 0xd2, 0x44, 0xde, 0x47, 0xc8, 0x1f, 0x9b, 0x1f,
	0x75, 0xc0, 0xfb, 0xb0, 0x39, 0x9c, 0x8a, 0x27, 0x3a, 0x07, 0x4a, 0xd0, 0xc9, 0x67, 0x85, 0xfc,
	0x11, 0x6c, 0x95, 0xe4, 0x5f, 0x38, 0x61, 0x9f, 0xc0, 0x86, 0x34, 0xfa, 0x80, 0x8d, 0xe3, 0xe4,
	0xbf, 0x3f, 0xe7, 0x33, 0xe8, 0x3a, 0x56, 0xce, 0x5b, 0x98, 0xfd, 0x42, 0x92, 0x6d, 0x78, 0xfa,
	0x66, 0x17, 0xea, 0x25, 0xe9, 0xfb, 0x28, 0x1e, 0x27, 0xd3, 0xd4, 0xe9, 0x25, 0x39, 0x92, 0x2a,
	0x7d, 0x4b, 0x06, 0xfe, 0x05, 0x90, 0xab, 0x75, 0xb9, 0x21, 0xdf, 0xca, 0xd3, 0xc5, 0xa6, 0x62,
	0xf5, 0xa3, 0xdf, 0xd5, 0x71, 0x5a, 0x51, 0x13, 0x67, 0xee, 0xc4, 0x5b, 0xee, 0xe4, 0x3d, 0xd8,
	0x96, 0x9a, 0x9f, 0x32, 0x3e, 0x66, 0xe2, 0x5c, 0x1d, 0x8b, 0x3f, 0x86, 0xa0, 0x4a, 0xe5, 0x02,
	0x4e, 0xef, 0x6a, 0x0b, 0x21, 0x1d, 0xb1, 0x33, 0xca, 0x17, 0xbd, 0xba, 0x25, 0xe4, 0x2d, 0x94,
	0xd0, 0x10, 0x6e, 0x54, 0x6a, 0x5e, 0xc0, 0xf9, 0x5f, 0x1e, 0x40, 0x48, 0x33, 0x41, 0xa6, 0x9c,
	0x24, 0xa2, 0xb4, 0x4b, 0xed, 0xd6, 0xac, 0x39, 0x5b, 0x73, 0x13, 0x1a, 0x9c, 0x88, 0x38, 0x19,
	0x9b, 0x5d, 0x6a, 0x4e, 0x72, 0xed, 0x93, 0x28, 0xe2, 0x34, 0xcb, 0xcc, 0x32, 0xb5, 0x47, 0x69,
	0x85, 0xa5, 0x34, 0x51, 0x5b, 0x74, 0x3d, 0x54, 0xff, 0xe8, 0x6d, 0xb8, 0x9a, 0x3e, 0x61, 0x82,
	0x9d, 0x70, 0xfa, 0x98, 0x72, 0x9a, 0x8c, 0xa8, 0xda, 0xa2, 0xad, 0xb0, 0xa3, 0xc8, 0xa1, 0xa5,
	0xca, 0x5b, 0x8c, 0x24, 0x54, 0xe8, 0x35, 0x0b, 0xb7, 0x50, 0xf0, 0x21, 0xd4, 0x2c, 0x4c, 0x60,
	0x67, 0x7e, 0x09, 0x39, 0xb5, 0xee, 0xcf, 0x34, 0xdf, 0x24, 0x31, 0xb7, 0xe1, 0x2d, 0xb5, 0x21,
	0x37, 0x7a, 0x4a, 0xc6, 0xf4, 0x44, 0x17, 0x94, 0x81, 0x1b, 0x92, 0xa2, 0x2a, 0x15, 0xdf, 0x83,
	0x6d, 0x35, 0xca, 0xaa, 0xdc, 0x2c, 0xe8, 0x7a, 0x8b, 0xba, 0x7f, 0x78, 0xb0, 0xbb, 0x24, 0x3e,
	0xf3, 0x54, 0x6f, 0x15, 0x86, 0x6b, 0xd7, 0xc4, 0x37, 0xd7, 0x31, 0xad, 0x74, 0xbb, 0xd0, 0x4a,
	0x7d, 0x77, 0xc4, 0x56, 0x9a, 0x3f, 0x7f, 0x7b, 0xfd, 0xe9, 0x41, 0xf3, 0xf3, 0x38, 0x13, 0x8c,
	0xcf, 0x4a, 0x45, 0xe0, 0x40, 0x97, 0x9a, 0x0b, 0x5d, 0x0a, 0xe0, 0x6d, 0x6d, 0x15, 0x78, 0xab,
	0x2f, 0x80, 0xb7, 0x17, 0x44, 0x57, 0x77, 0x20, 0x30, 0xb1, 0xea, 0xcb, 0x1e, 0xab, 0x70, 0x9e,
	0x8b, 0xb4, 0x7e, 0xf3, 0xe0, 0x46, 0xa5, 0x5e, 0xde, 0x2f, 0xee, 0x23, 0x74, 0x4c, 0x9a, 0x8c,
	0xc6, 0xff, 0xb8, 0xe4, 0x06, 0xff, 0xd4, 0xa0, 0x2d, 0x7d, 0x1f, 0x51, 0x7e, 0x16, 0x8f, 0x28,
	0xba, 0x07, 0x4d, 0x03, 0xad, 0xd0, 0x75, 0x67, 0x7e, 0xce, 0xd1, 0x63, 0xb0, 0xb9, 0x48, 0xd6,
	0x21, 0xe3, 0x2b, 0xe8, 0xab, 0x1c, 0x69, 0x1a, 0x58, 0x86, 0x76, 0x8a, 0xb2, 0x45, 0x70, 0x17,
	0xec, 0x2e, 0xe1, 0xe6, 0x06, 0x0f, 0x00, 0xe6, 0x88, 0x09, 0xf5, 0x1c, 0xf1, 0x02, 0xf4, 0x0a,
	0xb6, 0x2b, 0x38, 0xb9, 0x91, 0xef, 0x34, 0xec, 0x2a, 0x62, 0x15, 0xd4, 0x77, 0x54, 0x2a, 0x51,
	0x51, 0x70, 0x73, 0x85, 0x44, 0x6e, 0xfc, 0x43, 0x58, 0xb7, 0xe8, 0x04, 0xb9, 0x89, 0x71, 0x10,
	0x4c, 0xb0, 0x55, 0xa2, 0x5b, 0xf5, 0xc1, 0xdf, 0x1e, 0xb4, 0xd5, 0x1e, 0x33, 0xd9, 0xff, 0x12,
	0xda, 0x0e, 0x3e, 0x40, 0x36, 0x41, 0xd5, 0x38, 0x23, 0x78, 0x6d, 0x19, 0x3b, 0x0f, 0xef, 0x03,
	0xf0, 0xd5, 0x52, 0x47, 0x5b, 0x8e, 0xa8, 0x0b, 0x16, 0x82, 0x5e, 0x99, 0x91, 0x6b, 0x7f, 0x04,
	0x0d, 0xb9, 0x60, 0x8f, 0x53, 0xe4, 0x4a, 0x15, 0x36, 0x75, 0x9e, 0xfa, 0xf2, 0x36, 0xc6, 0x57,
	0x06, 0x0c, 0xba, 0xf3, 0x61, 0x60, 0xef, 0xf8, 0x2d, 0xb4, 0xdd, 0x79, 0xf5, 0x46, 0x69, 0xc0,
	0x94, 0x87, 0x66, 0xf0, 0xe6, 0x6a, 0xa1, 0xdc, 0x61, 0x0a, 0x1d, 0xd3, 0x23, 0xd6, 0xdb, 0xf7,
	0xf0, 0xaa, 0x14, 0x35, 0x54, 0xdb, 0x67, 0xe8, 0x66, 0xb1, 0xa3, 0x2a, 0x7a, 0x37, 0xc0, 0xab,
	0x44, 0xac, 0xc7, 0x1f, 0x1a, 0x4a, 0xe8, 0xfd, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x69,
	0x0d, 0xda, 0xa7, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	UserGet(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error)
	UserGetByEmail(ctx context.Context, in *UserGetByEmailRequest, opts ...grpc.CallOption) (*UserGetByEmailResponse, error)
	UserCreate(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error)
	UserVerifyPassword(ctx context.Context, in *UserVerifyPasswordRequest, opts ...grpc.CallOption) (*UserVerifyPasswordResponse, error)
	UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) UserGet(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error) {
	out := new(UserGetResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/UserGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserGetByEmail(ctx context.Context, in *UserGetByEmailRequest, opts ...grpc.CallOption) (*UserGetByEmailResponse, error) {
	out := new(UserGetByEmailResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/UserGetByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserCreate(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error) {
	out := new(UserCreateResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/UserCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserVerifyPassword(ctx context.Context, in *UserVerifyPasswordRequest, opts ...grpc.CallOption) (*UserVerifyPasswordResponse, error) {
	out := new(UserVerifyPasswordResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/UserVerifyPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/UserList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	UserGet(context.Context, *UserGetRequest) (*UserGetResponse, error)
	UserGetByEmail(context.Context, *UserGetByEmailRequest) (*UserGetByEmailResponse, error)
	UserCreate(context.Context, *UserCreateRequest) (*UserCreateResponse, error)
	UserVerifyPassword(context.Context, *UserVerifyPasswordRequest) (*UserVerifyPasswordResponse, error)
	UserList(context.Context, *UserListRequest) (*UserListResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) UserGet(ctx context.Context, req *UserGetRequest) (*UserGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGet not implemented")
}
func (*UnimplementedUserServiceServer) UserGetByEmail(ctx context.Context, req *UserGetByEmailRequest) (*UserGetByEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGetByEmail not implemented")
}
func (*UnimplementedUserServiceServer) UserCreate(ctx context.Context, req *UserCreateRequest) (*UserCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCreate not implemented")
}
func (*UnimplementedUserServiceServer) UserVerifyPassword(ctx context.Context, req *UserVerifyPasswordRequest) (*UserVerifyPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserVerifyPassword not implemented")
}
func (*UnimplementedUserServiceServer) UserList(ctx context.Context, req *UserListRequest) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserList not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_UserGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UserGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserGet(ctx, req.(*UserGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserGetByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserGetByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UserGetByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserGetByEmail(ctx, req.(*UserGetByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UserCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserCreate(ctx, req.(*UserCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserVerifyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserVerifyPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserVerifyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UserVerifyPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserVerifyPassword(ctx, req.(*UserVerifyPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserList(ctx, req.(*UserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserGet",
			Handler:    _UserService_UserGet_Handler,
		},
		{
			MethodName: "UserGetByEmail",
			Handler:    _UserService_UserGetByEmail_Handler,
		},
		{
			MethodName: "UserCreate",
			Handler:    _UserService_UserCreate_Handler,
		},
		{
			MethodName: "UserVerifyPassword",
			Handler:    _UserService_UserVerifyPassword_Handler,
		},
		{
			MethodName: "UserList",
			Handler:    _UserService_UserList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/demo.proto",
}

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	VerifyToken(ctx context.Context, in *AuthVerifyTokenRequest, opts ...grpc.CallOption) (*AuthVerifyTokenResponse, error)
	Login(ctx context.Context, in *AuthLoginRequest, opts ...grpc.CallOption) (*AuthLoginResponse, error)
	SignUp(ctx context.Context, in *AuthSignupRequest, opts ...grpc.CallOption) (*AuthSignupResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) VerifyToken(ctx context.Context, in *AuthVerifyTokenRequest, opts ...grpc.CallOption) (*AuthVerifyTokenResponse, error) {
	out := new(AuthVerifyTokenResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/VerifyToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *AuthLoginRequest, opts ...grpc.CallOption) (*AuthLoginResponse, error) {
	out := new(AuthLoginResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SignUp(ctx context.Context, in *AuthSignupRequest, opts ...grpc.CallOption) (*AuthSignupResponse, error) {
	out := new(AuthSignupResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	VerifyToken(context.Context, *AuthVerifyTokenRequest) (*AuthVerifyTokenResponse, error)
	Login(context.Context, *AuthLoginRequest) (*AuthLoginResponse, error)
	SignUp(context.Context, *AuthSignupRequest) (*AuthSignupResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) VerifyToken(ctx context.Context, req *AuthVerifyTokenRequest) (*AuthVerifyTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *AuthLoginRequest) (*AuthLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServiceServer) SignUp(ctx context.Context, req *AuthSignupRequest) (*AuthSignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthVerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/VerifyToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyToken(ctx, req.(*AuthVerifyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*AuthLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthSignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignUp(ctx, req.(*AuthSignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _AuthService_VerifyToken_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _AuthService_SignUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/demo.proto",
}

// RestaurantServiceClient is the client API for RestaurantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RestaurantServiceClient interface {
	ListByCoord(ctx context.Context, in *RestaurantListByCoordRequest, opts ...grpc.CallOption) (*RestaurantListByCoordResponse, error)
}

type restaurantServiceClient struct {
	cc *grpc.ClientConn
}

func NewRestaurantServiceClient(cc *grpc.ClientConn) RestaurantServiceClient {
	return &restaurantServiceClient{cc}
}

func (c *restaurantServiceClient) ListByCoord(ctx context.Context, in *RestaurantListByCoordRequest, opts ...grpc.CallOption) (*RestaurantListByCoordResponse, error) {
	out := new(RestaurantListByCoordResponse)
	err := c.cc.Invoke(ctx, "/proto.RestaurantService/ListByCoord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantServiceServer is the server API for RestaurantService service.
type RestaurantServiceServer interface {
	ListByCoord(context.Context, *RestaurantListByCoordRequest) (*RestaurantListByCoordResponse, error)
}

// UnimplementedRestaurantServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRestaurantServiceServer struct {
}

func (*UnimplementedRestaurantServiceServer) ListByCoord(ctx context.Context, req *RestaurantListByCoordRequest) (*RestaurantListByCoordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByCoord not implemented")
}

func RegisterRestaurantServiceServer(s *grpc.Server, srv RestaurantServiceServer) {
	s.RegisterService(&_RestaurantService_serviceDesc, srv)
}

func _RestaurantService_ListByCoord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestaurantListByCoordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).ListByCoord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RestaurantService/ListByCoord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).ListByCoord(ctx, req.(*RestaurantListByCoordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RestaurantService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RestaurantService",
	HandlerType: (*RestaurantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListByCoord",
			Handler:    _RestaurantService_ListByCoord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/demo.proto",
}

// HistoryServiceClient is the client API for HistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HistoryServiceClient interface {
	ListHistoryByUserId(ctx context.Context, in *HistoryListByUserIdRequest, opts ...grpc.CallOption) (*HistoryListByUserIdResponse, error)
}

type historyServiceClient struct {
	cc *grpc.ClientConn
}

func NewHistoryServiceClient(cc *grpc.ClientConn) HistoryServiceClient {
	return &historyServiceClient{cc}
}

func (c *historyServiceClient) ListHistoryByUserId(ctx context.Context, in *HistoryListByUserIdRequest, opts ...grpc.CallOption) (*HistoryListByUserIdResponse, error) {
	out := new(HistoryListByUserIdResponse)
	err := c.cc.Invoke(ctx, "/proto.HistoryService/ListHistoryByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryServiceServer is the server API for HistoryService service.
type HistoryServiceServer interface {
	ListHistoryByUserId(context.Context, *HistoryListByUserIdRequest) (*HistoryListByUserIdResponse, error)
}

// UnimplementedHistoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHistoryServiceServer struct {
}

func (*UnimplementedHistoryServiceServer) ListHistoryByUserId(ctx context.Context, req *HistoryListByUserIdRequest) (*HistoryListByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHistoryByUserId not implemented")
}

func RegisterHistoryServiceServer(s *grpc.Server, srv HistoryServiceServer) {
	s.RegisterService(&_HistoryService_serviceDesc, srv)
}

func _HistoryService_ListHistoryByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryListByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).ListHistoryByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HistoryService/ListHistoryByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).ListHistoryByUserId(ctx, req.(*HistoryListByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HistoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HistoryService",
	HandlerType: (*HistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListHistoryByUserId",
			Handler:    _HistoryService_ListHistoryByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/demo.proto",
}
