// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/demo.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Meta struct {
	Page                 *MetaPage `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{0}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetPage() *MetaPage {
	if m != nil {
		return m.Page
	}
	return nil
}

type MetaPage struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Current              int32    `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	Prev                 int32    `protobuf:"varint,3,opt,name=prev,proto3" json:"prev,omitempty"`
	Next                 int32    `protobuf:"varint,4,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaPage) Reset()         { *m = MetaPage{} }
func (m *MetaPage) String() string { return proto.CompactTextString(m) }
func (*MetaPage) ProtoMessage()    {}
func (*MetaPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{1}
}

func (m *MetaPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaPage.Unmarshal(m, b)
}
func (m *MetaPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaPage.Marshal(b, m, deterministic)
}
func (m *MetaPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaPage.Merge(m, src)
}
func (m *MetaPage) XXX_Size() int {
	return xxx_messageInfo_MetaPage.Size(m)
}
func (m *MetaPage) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaPage.DiscardUnknown(m)
}

var xxx_messageInfo_MetaPage proto.InternalMessageInfo

func (m *MetaPage) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *MetaPage) GetCurrent() int32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *MetaPage) GetPrev() int32 {
	if m != nil {
		return m.Prev
	}
	return 0
}

func (m *MetaPage) GetNext() int32 {
	if m != nil {
		return m.Next
	}
	return 0
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type UserGetRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetRequest) Reset()         { *m = UserGetRequest{} }
func (m *UserGetRequest) String() string { return proto.CompactTextString(m) }
func (*UserGetRequest) ProtoMessage()    {}
func (*UserGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{5}
}

func (m *UserGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetRequest.Unmarshal(m, b)
}
func (m *UserGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetRequest.Marshal(b, m, deterministic)
}
func (m *UserGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetRequest.Merge(m, src)
}
func (m *UserGetRequest) XXX_Size() int {
	return xxx_messageInfo_UserGetRequest.Size(m)
}
func (m *UserGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetRequest proto.InternalMessageInfo

func (m *UserGetRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserGetResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetResponse) Reset()         { *m = UserGetResponse{} }
func (m *UserGetResponse) String() string { return proto.CompactTextString(m) }
func (*UserGetResponse) ProtoMessage()    {}
func (*UserGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{6}
}

func (m *UserGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetResponse.Unmarshal(m, b)
}
func (m *UserGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetResponse.Marshal(b, m, deterministic)
}
func (m *UserGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetResponse.Merge(m, src)
}
func (m *UserGetResponse) XXX_Size() int {
	return xxx_messageInfo_UserGetResponse.Size(m)
}
func (m *UserGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetResponse proto.InternalMessageInfo

func (m *UserGetResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserGetResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserGetResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserGetByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetByEmailRequest) Reset()         { *m = UserGetByEmailRequest{} }
func (m *UserGetByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*UserGetByEmailRequest) ProtoMessage()    {}
func (*UserGetByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{7}
}

func (m *UserGetByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetByEmailRequest.Unmarshal(m, b)
}
func (m *UserGetByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetByEmailRequest.Marshal(b, m, deterministic)
}
func (m *UserGetByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetByEmailRequest.Merge(m, src)
}
func (m *UserGetByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_UserGetByEmailRequest.Size(m)
}
func (m *UserGetByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetByEmailRequest proto.InternalMessageInfo

func (m *UserGetByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserGetByEmailResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetByEmailResponse) Reset()         { *m = UserGetByEmailResponse{} }
func (m *UserGetByEmailResponse) String() string { return proto.CompactTextString(m) }
func (*UserGetByEmailResponse) ProtoMessage()    {}
func (*UserGetByEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{8}
}

func (m *UserGetByEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetByEmailResponse.Unmarshal(m, b)
}
func (m *UserGetByEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetByEmailResponse.Marshal(b, m, deterministic)
}
func (m *UserGetByEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetByEmailResponse.Merge(m, src)
}
func (m *UserGetByEmailResponse) XXX_Size() int {
	return xxx_messageInfo_UserGetByEmailResponse.Size(m)
}
func (m *UserGetByEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetByEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetByEmailResponse proto.InternalMessageInfo

func (m *UserGetByEmailResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserGetByEmailResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserGetByEmailResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserCreateRequest struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateRequest) Reset()         { *m = UserCreateRequest{} }
func (m *UserCreateRequest) String() string { return proto.CompactTextString(m) }
func (*UserCreateRequest) ProtoMessage()    {}
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{9}
}

func (m *UserCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateRequest.Unmarshal(m, b)
}
func (m *UserCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateRequest.Marshal(b, m, deterministic)
}
func (m *UserCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateRequest.Merge(m, src)
}
func (m *UserCreateRequest) XXX_Size() int {
	return xxx_messageInfo_UserCreateRequest.Size(m)
}
func (m *UserCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateRequest proto.InternalMessageInfo

func (m *UserCreateRequest) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserCreateResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateResponse) Reset()         { *m = UserCreateResponse{} }
func (m *UserCreateResponse) String() string { return proto.CompactTextString(m) }
func (*UserCreateResponse) ProtoMessage()    {}
func (*UserCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{10}
}

func (m *UserCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateResponse.Unmarshal(m, b)
}
func (m *UserCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateResponse.Marshal(b, m, deterministic)
}
func (m *UserCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateResponse.Merge(m, src)
}
func (m *UserCreateResponse) XXX_Size() int {
	return xxx_messageInfo_UserCreateResponse.Size(m)
}
func (m *UserCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateResponse proto.InternalMessageInfo

func (m *UserCreateResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserCreateResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserCreateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserVerifyPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserVerifyPasswordRequest) Reset()         { *m = UserVerifyPasswordRequest{} }
func (m *UserVerifyPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UserVerifyPasswordRequest) ProtoMessage()    {}
func (*UserVerifyPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{11}
}

func (m *UserVerifyPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVerifyPasswordRequest.Unmarshal(m, b)
}
func (m *UserVerifyPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVerifyPasswordRequest.Marshal(b, m, deterministic)
}
func (m *UserVerifyPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVerifyPasswordRequest.Merge(m, src)
}
func (m *UserVerifyPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UserVerifyPasswordRequest.Size(m)
}
func (m *UserVerifyPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVerifyPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserVerifyPasswordRequest proto.InternalMessageInfo

func (m *UserVerifyPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserVerifyPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserVerifyPasswordResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserVerifyPasswordResponse) Reset()         { *m = UserVerifyPasswordResponse{} }
func (m *UserVerifyPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UserVerifyPasswordResponse) ProtoMessage()    {}
func (*UserVerifyPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{12}
}

func (m *UserVerifyPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVerifyPasswordResponse.Unmarshal(m, b)
}
func (m *UserVerifyPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVerifyPasswordResponse.Marshal(b, m, deterministic)
}
func (m *UserVerifyPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVerifyPasswordResponse.Merge(m, src)
}
func (m *UserVerifyPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UserVerifyPasswordResponse.Size(m)
}
func (m *UserVerifyPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVerifyPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserVerifyPasswordResponse proto.InternalMessageInfo

func (m *UserVerifyPasswordResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *UserVerifyPasswordResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserVerifyPasswordResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Meta)(nil), "proto.Meta")
	proto.RegisterType((*MetaPage)(nil), "proto.MetaPage")
	proto.RegisterType((*Error)(nil), "proto.Error")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*UserGetRequest)(nil), "proto.UserGetRequest")
	proto.RegisterType((*UserGetResponse)(nil), "proto.UserGetResponse")
	proto.RegisterType((*UserGetByEmailRequest)(nil), "proto.UserGetByEmailRequest")
	proto.RegisterType((*UserGetByEmailResponse)(nil), "proto.UserGetByEmailResponse")
	proto.RegisterType((*UserCreateRequest)(nil), "proto.UserCreateRequest")
	proto.RegisterType((*UserCreateResponse)(nil), "proto.UserCreateResponse")
	proto.RegisterType((*UserVerifyPasswordRequest)(nil), "proto.UserVerifyPasswordRequest")
	proto.RegisterType((*UserVerifyPasswordResponse)(nil), "proto.UserVerifyPasswordResponse")
}

func init() { proto.RegisterFile("proto/demo.proto", fileDescriptor_bf10b39337e838aa) }

var fileDescriptor_bf10b39337e838aa = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x25, 0xa9, 0x9d, 0x8f, 0x09, 0x6a, 0x61, 0xd5, 0x16, 0xd7, 0xa2, 0x22, 0x2c, 0x97, 0x22,
	0x44, 0x91, 0x02, 0x5c, 0xb8, 0x95, 0x2a, 0x42, 0x1c, 0x2a, 0xaa, 0x45, 0x70, 0xe1, 0x50, 0x6d,
	0xe3, 0xa1, 0xb2, 0x14, 0xc7, 0x66, 0xbd, 0x49, 0x08, 0x07, 0x7e, 0x08, 0xbf, 0x85, 0x1f, 0x87,
	0x66, 0xbc, 0x76, 0xec, 0x2a, 0x94, 0x0b, 0xea, 0x29, 0x33, 0xf3, 0xde, 0x8c, 0xdf, 0xce, 0xbc,
	0xc0, 0xbd, 0xcc, 0xa4, 0x36, 0x7d, 0x11, 0x61, 0x92, 0x1e, 0x73, 0x28, 0x7c, 0xfe, 0x91, 0xcf,
	0xc0, 0x3b, 0x43, 0xab, 0xc5, 0x13, 0xf0, 0x32, 0x7d, 0x85, 0x41, 0x6b, 0xd8, 0x3a, 0x1a, 0x8c,
	0x76, 0x0a, 0xd2, 0x31, 0x41, 0xe7, 0xfa, 0x0a, 0x15, 0x83, 0xf2, 0x12, 0x7a, 0x65, 0x45, 0xec,
	0x82, 0x6f, 0x53, 0xab, 0xa7, 0xdc, 0xe1, 0xab, 0x22, 0x11, 0x01, 0x74, 0x27, 0x73, 0x63, 0x70,
	0x66, 0x83, 0x36, 0xd7, 0xcb, 0x54, 0x08, 0xf0, 0x32, 0x83, 0x8b, 0x60, 0x8b, 0xcb, 0x1c, 0x53,
	0x6d, 0x86, 0xdf, 0x6d, 0xe0, 0x15, 0x35, 0x8a, 0xe5, 0x6b, 0xf0, 0xc7, 0xc6, 0xa4, 0x86, 0xc0,
	0x49, 0x1a, 0xa1, 0x9b, 0xcf, 0x31, 0x8d, 0x4f, 0x30, 0xcf, 0x49, 0x28, 0x8d, 0xef, 0xab, 0x32,
	0x95, 0x5d, 0xf0, 0xc7, 0x49, 0x66, 0x57, 0xf2, 0x57, 0x0b, 0xbc, 0x4f, 0x39, 0x1a, 0xb1, 0x0d,
	0xed, 0x38, 0xe2, 0xee, 0xbe, 0x6a, 0xc7, 0x11, 0x09, 0xc6, 0x44, 0xc7, 0x53, 0xd7, 0x59, 0x24,
	0x2c, 0x41, 0x27, 0xc8, 0xb2, 0xfa, 0x8a, 0x63, 0x11, 0x42, 0x2f, 0xd3, 0x79, 0xbe, 0x4c, 0x4d,
	0xc4, 0xd2, 0xfa, 0xaa, 0xca, 0xc5, 0x21, 0xc0, 0xc4, 0xa0, 0xb6, 0x18, 0x5d, 0x68, 0x1b, 0xf8,
	0xc3, 0xd6, 0xd1, 0x96, 0xea, 0xbb, 0xca, 0x89, 0x25, 0x78, 0x9e, 0x45, 0x25, 0xdc, 0x29, 0x60,
	0x57, 0x39, 0xb1, 0xf2, 0x29, 0x6c, 0x93, 0xb6, 0x77, 0x68, 0x15, 0x7e, 0x9b, 0x63, 0x6e, 0xc5,
	0x03, 0xe8, 0xce, 0x73, 0x34, 0x17, 0x95, 0xd4, 0x0e, 0xa5, 0xef, 0x23, 0xb9, 0x84, 0x9d, 0x8a,
	0x9a, 0x67, 0xe9, 0x2c, 0x47, 0xf1, 0x08, 0xbc, 0x48, 0x5b, 0xed, 0x6e, 0x34, 0x70, 0x37, 0x22,
	0x96, 0x62, 0x80, 0x08, 0x09, 0x5a, 0xcd, 0x2f, 0x5c, 0x13, 0xe8, 0x64, 0x8a, 0x01, 0x21, 0xc1,
	0x47, 0x5a, 0x2e, 0x3f, 0x77, 0x30, 0xba, 0xeb, 0x18, 0xbc, 0x70, 0x55, 0x40, 0xf2, 0x39, 0xec,
	0xb9, 0x0f, 0xbf, 0x5d, 0x8d, 0x69, 0x47, 0xa5, 0xd4, 0x6a, 0x81, 0xad, 0xda, 0x02, 0xe5, 0x4f,
	0xd8, 0xbf, 0x4e, 0xbf, 0x55, 0xb9, 0xaf, 0xe0, 0x3e, 0x8d, 0x3c, 0xe5, 0x13, 0x94, 0x52, 0xff,
	0xf5, 0x69, 0xf9, 0x03, 0x44, 0xbd, 0xeb, 0x56, 0x15, 0x9f, 0xc1, 0x01, 0x8d, 0xfc, 0x8c, 0x26,
	0xfe, 0xba, 0x3a, 0x77, 0xc6, 0xba, 0x71, 0xc9, 0x0d, 0x47, 0xb6, 0x9b, 0x8e, 0x94, 0x4b, 0x08,
	0x37, 0x8d, 0x73, 0x4f, 0xda, 0x05, 0x7f, 0xa1, 0xa7, 0xce, 0x5d, 0x3d, 0x55, 0x24, 0xff, 0xe5,
	0x1d, 0xa3, 0xdf, 0x6d, 0x18, 0xd0, 0x97, 0x3f, 0xa2, 0x59, 0xc4, 0x13, 0x14, 0x6f, 0xa0, 0xeb,
	0x9c, 0x20, 0xf6, 0x6a, 0xab, 0x5b, 0x9b, 0x3d, 0xdc, 0xbf, 0x5e, 0x2e, 0x44, 0xca, 0x3b, 0xe2,
	0x43, 0xf5, 0xc7, 0x70, 0x2e, 0x12, 0x0f, 0x9b, 0xdc, 0xa6, 0x17, 0xc3, 0xc3, 0xbf, 0xa0, 0xd5,
	0xc0, 0x53, 0x80, 0xf5, 0x81, 0x45, 0x50, 0xa3, 0x37, 0x9c, 0x12, 0x1e, 0x6c, 0x40, 0xaa, 0x21,
	0x5f, 0x0a, 0x97, 0x34, 0x57, 0x2b, 0x86, 0xb5, 0x96, 0x8d, 0x47, 0x0c, 0x1f, 0xdf, 0xc0, 0x28,
	0x87, 0x5f, 0x76, 0x98, 0xf3, 0xf2, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0x9d, 0x9e, 0x3d,
	0x9b, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	UserGet(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error)
	UserGetByEmail(ctx context.Context, in *UserGetByEmailRequest, opts ...grpc.CallOption) (*UserGetByEmailResponse, error)
	UserCreate(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error)
	UserVerifyPassword(ctx context.Context, in *UserVerifyPasswordRequest, opts ...grpc.CallOption) (*UserVerifyPasswordResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) UserGet(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error) {
	out := new(UserGetResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/UserGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserGetByEmail(ctx context.Context, in *UserGetByEmailRequest, opts ...grpc.CallOption) (*UserGetByEmailResponse, error) {
	out := new(UserGetByEmailResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/UserGetByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserCreate(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error) {
	out := new(UserCreateResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/UserCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserVerifyPassword(ctx context.Context, in *UserVerifyPasswordRequest, opts ...grpc.CallOption) (*UserVerifyPasswordResponse, error) {
	out := new(UserVerifyPasswordResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/UserVerifyPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	UserGet(context.Context, *UserGetRequest) (*UserGetResponse, error)
	UserGetByEmail(context.Context, *UserGetByEmailRequest) (*UserGetByEmailResponse, error)
	UserCreate(context.Context, *UserCreateRequest) (*UserCreateResponse, error)
	UserVerifyPassword(context.Context, *UserVerifyPasswordRequest) (*UserVerifyPasswordResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) UserGet(ctx context.Context, req *UserGetRequest) (*UserGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGet not implemented")
}
func (*UnimplementedUserServiceServer) UserGetByEmail(ctx context.Context, req *UserGetByEmailRequest) (*UserGetByEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGetByEmail not implemented")
}
func (*UnimplementedUserServiceServer) UserCreate(ctx context.Context, req *UserCreateRequest) (*UserCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCreate not implemented")
}
func (*UnimplementedUserServiceServer) UserVerifyPassword(ctx context.Context, req *UserVerifyPasswordRequest) (*UserVerifyPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserVerifyPassword not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_UserGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UserGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserGet(ctx, req.(*UserGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserGetByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserGetByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UserGetByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserGetByEmail(ctx, req.(*UserGetByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UserCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserCreate(ctx, req.(*UserCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserVerifyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserVerifyPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserVerifyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UserVerifyPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserVerifyPassword(ctx, req.(*UserVerifyPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserGet",
			Handler:    _UserService_UserGet_Handler,
		},
		{
			MethodName: "UserGetByEmail",
			Handler:    _UserService_UserGetByEmail_Handler,
		},
		{
			MethodName: "UserCreate",
			Handler:    _UserService_UserCreate_Handler,
		},
		{
			MethodName: "UserVerifyPassword",
			Handler:    _UserService_UserVerifyPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/demo.proto",
}
